export const SET_DARK_MODE = "SET_DARK_MODE";
export const SET_SNACKBAR = "SET_SNACKBAR";

export const SET_USER = "SET_USER";
export const SET_BILLS = "SET_BILLS";
export const SET_CHALANS = "SET_CHALLANS";

export const SET_GETTING_CUSTOMERS = "SET_GETTING_CUSTOMERS";
export const SET_CUSTOMERS = "SET_CUSTOMERS";

export const SET_GETTING_PRODUCTS = "SET_GETTING_PRODUCTS";
export const SET_PRODUCTS = "SET_PRODUCTS";

export const SET_GETTING_STATES = "SET_GETTING_STATES";
export const SET_STATES = "SET_STATES";
